name: "LLM code reviewer"
description: "automatic code review by LLM"
inputs:
  GITHUB_TOKEN:
    required: true
  LLM_API_KEY:
    description: "api key for calling LLM API."
    required: true
  LLM_API_MODEL:
    description: "model name to use."
    required: false
    default: "claude-3-haiku-20240307"
  exclude:
    description: "exclude files from the diff analysis by Glob pattern"
    required: false
    default: ""
runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    with:
      node-version: 20
      cache: 'npm'
  - run: npm install
    shell: bash
  - run: node build/test.js
    shell: bash
