name: 'LLM code reviewer'
description: 'automatic code review by LLM'
inputs:
  GITHUB_TOKEN:
    required: true
  LLM_API_KEY:
    description: 'api key for calling LLM API.'
    required: true
  LLM_API_CHAT:
    description: 'model name to infer.'
    required: false
    default: 'gpt-3.5-turbo'
  LLM_API_EMBEDDING:
    description: 'model name to embed.'
    required: false
    default: 'text-embedding-3-large'
  PINECONE_API_KEY:
    description: 'api key for calling Pinecone API.'
    required: true
  PINECONE_INDEX_NAME:
    description: 'index name for Pinecone.'
    required: true
  PINECONE_NAMESPACE:
    description: 'namespace for Pinecone.'
    required: true
  exclude:
    description: 'exclude files from the diff analysis by Glob pattern'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
