name: LLM code reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: LLM code reviewer
        uses: han-kimm/llm-review@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_API_MODEL: "claude-3-haiku-20240307"
          exclude: "**/*.json, **/*.md"
